# python tools/pcd_vis_single_frame_demo.py      --model_file outputs/pointpillars_zw_car5/best_model/pointpillars.pdmodel      --params_file outputs/pointpillars_zw_car5/best_model/pointpillars.pdiparams      --lidar_file datasets/zw_0830/load1-low-speed_sync/lidar_bin_xyzi/      --image_dir datasets/zw_0830/load1-low-speed_sync/camera/front     --calib_file datasets/zw_anno_0914/KITTI_format/training/calib/load1-low-speed_sync_005980.txt      --point_cloud_range 0 -39.68 -5 69.12 39.68 5      --voxel_size .16 .16 10      --max_points_in_voxel 32      --max_voxel_num 40000 --results_dir 'res/load1-low-speed_sync'

# python tools/pcd_vis_single_frame_demo.py      --model_file outputs/pointpillars_zw_car5/best_model/pointpillars.pdmodel      --params_file outputs/pointpillars_zw_car5/best_model/pointpillars.pdiparams      --lidar_file datasets/zw_0830/load3-mid-speed-night_sync/lidar_bin_xyzi/      --image_dir datasets/zw_0830/load3-mid-speed-night_sync/camera/front     --calib_file datasets/zw_anno_0914/KITTI_format/training/calib/load1-low-speed_sync_005980.txt      --point_cloud_range 0 -39.68 -5 69.12 39.68 5      --voxel_size .16 .16 10      --max_points_in_voxel 32      --max_voxel_num 40000 --results_dir 'res/load3-mid-speed-night_sync'

# python tools/pcd_vis_single_frame_demo.py      --model_file outputs/pointpillars_zw_car5/best_model/pointpillars.pdmodel      --params_file outputs/pointpillars_zw_car5/best_model/pointpillars.pdiparams      --lidar_file datasets/zw_0830/load3-mid-speed_sync/lidar_bin_xyzi/      --image_dir datasets/zw_0830/load3-mid-speed_sync/camera/front     --calib_file datasets/zw_anno_0914/KITTI_format/training/calib/load1-low-speed_sync_005980.txt      --point_cloud_range 0 -39.68 -5 69.12 39.68 5      --voxel_size .16 .16 10      --max_points_in_voxel 32      --max_voxel_num 40000 --results_dir 'res/load3-mid-speed_sync'

#/home/gygwg/workspace/Paddle3D/datasets/zw_0830/perception-dataset/PKU-Around_sync
# python tools/pcd_vis_single_frame_demo.py      --model_file outputs/pointpillars_zw_car5/best_model/pointpillars.pdmodel      --params_file outputs/pointpillars_zw_car5/best_model/pointpillars.pdiparams      --lidar_file datasets/zw_0830/perception-dataset/PKU-Around_sync/lidar_bin_xyzi/      --image_dir datasets/zw_0830/perception-dataset/PKU-Around_sync/camera/front     --calib_file datasets/zw_anno_0914/KITTI_format/training/calib/load1-low-speed_sync_005980.txt      --point_cloud_range 0 -39.68 -5 69.12 39.68 5      --voxel_size .16 .16 10      --max_points_in_voxel 32      --max_voxel_num 40000 --results_dir 'res/perception-dataset/PKU-Around_sync'

python tools/pcd_vis_single_frame_demo.py      --model_file outputs/pointpillars_zw_car5/best_model/pointpillars.pdmodel      --params_file outputs/pointpillars_zw_car5/best_model/pointpillars.pdiparams      --lidar_file datasets/zw_0830/perception-dataset/PKU-Inside_sync/lidar_bin_xyzi/      --image_dir datasets/zw_0830/perception-dataset/PKU-Inside_sync/camera/front     --calib_file datasets/zw_anno_0914/KITTI_format/training/calib/load1-low-speed_sync_005980.txt      --point_cloud_range 0 -39.68 -5 69.12 39.68 5      --voxel_size .16 .16 10      --max_points_in_voxel 32      --max_voxel_num 40000 --results_dir 'res/perception-dataset/PKU-Inside_sync'

python tools/pcd_vis_single_frame_demo.py      --model_file outputs/pointpillars_zw_car5/best_model/pointpillars.pdmodel      --params_file outputs/pointpillars_zw_car5/best_model/pointpillars.pdiparams      --lidar_file datasets/zw_0830/perception-dataset/Target-Tank_sync/lidar_bin_xyzi/      --image_dir datasets/zw_0830/perception-dataset/Target-Tank_sync/camera/front     --calib_file datasets/zw_anno_0914/KITTI_format/training/calib/load1-low-speed_sync_005980.txt      --point_cloud_range 0 -39.68 -5 69.12 39.68 5      --voxel_size .16 .16 10      --max_points_in_voxel 32      --max_voxel_num 40000 --results_dir 'res/perception-dataset/Target-Tank_sync'

python tools/pcd_vis_single_frame_demo.py      --model_file outputs/pointpillars_zw_car5/best_model/pointpillars.pdmodel      --params_file outputs/pointpillars_zw_car5/best_model/pointpillars.pdiparams      --lidar_file datasets/zw_0830/perception-dataset/Terrain_Cliff_Wall_sync/lidar_bin_xyzi/      --image_dir datasets/zw_0830/perception-dataset/Terrain_Cliff_Wall_sync/camera/front     --calib_file datasets/zw_anno_0914/KITTI_format/training/calib/load1-low-speed_sync_005980.txt      --point_cloud_range 0 -39.68 -5 69.12 39.68 5      --voxel_size .16 .16 10      --max_points_in_voxel 32      --max_voxel_num 40000 --results_dir 'res/perception-dataset/Terrain_Cliff_Wall_sync'

python tools/pcd_vis_single_frame_demo.py      --model_file outputs/pointpillars_zw_car5/best_model/pointpillars.pdmodel      --params_file outputs/pointpillars_zw_car5/best_model/pointpillars.pdiparams      --lidar_file datasets/zw_0830/perception-dataset/Terrain-Convex_cone_sync/lidar_bin_xyzi/      --image_dir datasets/zw_0830/perception-dataset/Terrain-Convex_cone_sync/camera/front     --calib_file datasets/zw_anno_0914/KITTI_format/training/calib/load1-low-speed_sync_005980.txt      --point_cloud_range 0 -39.68 -5 69.12 39.68 5      --voxel_size .16 .16 10      --max_points_in_voxel 32      --max_voxel_num 40000 --results_dir 'res/perception-dataset/Terrain-Convex_cone_sync'

python tools/pcd_vis_single_frame_demo.py      --model_file outputs/pointpillars_zw_car5/best_model/pointpillars.pdmodel      --params_file outputs/pointpillars_zw_car5/best_model/pointpillars.pdiparams      --lidar_file datasets/zw_0830/perception-dataset/Terrain-other_sync/lidar_bin_xyzi/      --image_dir datasets/zw_0830/perception-dataset/Terrain-other_sync/camera/front     --calib_file datasets/zw_anno_0914/KITTI_format/training/calib/load1-low-speed_sync_005980.txt      --point_cloud_range 0 -39.68 -5 69.12 39.68 5      --voxel_size .16 .16 10      --max_points_in_voxel 32      --max_voxel_num 40000 --results_dir 'res/perception-dataset/Terrain-other_sync'

python tools/pcd_vis_single_frame_demo.py      --model_file outputs/pointpillars_zw_car5/best_model/pointpillars.pdmodel      --params_file outputs/pointpillars_zw_car5/best_model/pointpillars.pdiparams      --lidar_file datasets/zw_0830/perception-dataset/Terrain-Steep_slope_sync/lidar_bin_xyzi/      --image_dir datasets/zw_0830/perception-dataset/Terrain-Steep_slope_sync/camera/front     --calib_file datasets/zw_anno_0914/KITTI_format/training/calib/load1-low-speed_sync_005980.txt      --point_cloud_range 0 -39.68 -5 69.12 39.68 5      --voxel_size .16 .16 10      --max_points_in_voxel 32      --max_voxel_num 40000 --results_dir 'res/perception-dataset/Terrain-Steep_slope_sync'

python tools/pcd_vis_single_frame_demo.py      --model_file outputs/pointpillars_zw_car5/best_model/pointpillars.pdmodel      --params_file outputs/pointpillars_zw_car5/best_model/pointpillars.pdiparams      --lidar_file datasets/zw_0830/perception-dataset/Terrain-Trench_sync/lidar_bin_xyzi/      --image_dir datasets/zw_0830/perception-dataset/Terrain-Trench_sync/camera/front     --calib_file datasets/zw_anno_0914/KITTI_format/training/calib/load1-low-speed_sync_005980.txt      --point_cloud_range 0 -39.68 -5 69.12 39.68 5      --voxel_size .16 .16 10      --max_points_in_voxel 32      --max_voxel_num 40000 --results_dir 'res/perception-dataset/Terrain-Trench_sync'

python tools/pcd_vis_single_frame_demo.py      --model_file outputs/pointpillars_zw_car5/best_model/pointpillars.pdmodel      --params_file outputs/pointpillars_zw_car5/best_model/pointpillars.pdiparams      --lidar_file datasets/zw_0830/perception-dataset/Turnel_sync/lidar_bin_xyzi/      --image_dir datasets/zw_0830/perception-dataset/Turnel_sync/camera/front     --calib_file datasets/zw_anno_0914/KITTI_format/training/calib/load1-low-speed_sync_005980.txt      --point_cloud_range 0 -39.68 -5 69.12 39.68 5      --voxel_size .16 .16 10      --max_points_in_voxel 32      --max_voxel_num 40000 --results_dir 'res/perception-dataset/Turnel_sync'
